---
steps:
  - name: gcr.io/cloud-builders/docker
    args:
      - build
      - -t
      - us-central1-docker.pkg.dev/trainocat-1771997762221/notes-repo/notes-app
      - .
  - name: gcr.io/cloud-builders/docker
    args:
      - push
      - us-central1-docker.pkg.dev/trainocat-1771997762221/notes-repo/notes-app
images:
  - us-central1-docker.pkg.dev/trainocat-1771997762221/notes-repo/notes-app
